### PR TITLE
Add the finalized key stories text to the figure #202

### PR DESCRIPTION
**Pull request by mwernimont**
Mobile (my phone)
screenshot_2018-04-24-11-13-09
screenshot_2018-04-24-11-13-15
Desktop
screen shot 2018-04-24 at 11 15 37 am

Talked to @lindsaycarr and we discussed trying to just split the figure in half and stacking the two on mobile.  I think its a huge improvement compared to what it was in the readability department.

### CODE REVIEW

**Comment by lindsaycarr** [comment]
Marty came and showed me how it looks on his phone right now and text size feels fine to me. I wish I could pinch and zoom on just that single fig (like zooming into the whole webpage) but we disabled that so that people couldn't do it on the main fig.

**Comment by aappling-usgs** [comment]
Per our group Slack convo, Marty is gonna try to squeeze up the font size on mobile a little more, putting in effort within reason given the approaching deadline.

I really like the overall look of the desktop pie map! Information rich, colorful, and nice placement and shaping of the text blocks.

**Comment by mwernimont** [comment]
screenshot_2018-04-24-13-08-02

**Comment by mwernimont** [comment]
Larger font for the mobile figures and I evened up the split in the country to avoid the size difference shrinking the text on either figure.

**Pull request merged**
