### PR TITLE
Mobile buttons and tooltip style to match button roundness.

### PR DESCRIPTION
**Pull request by mwernimont**
We have the 5 buttons fitting on mobile decently. There will be adjusting if we do add the 6th button, as the text is as small as I can personally allow.  Since it will be even amount of buttons with 6 we could stack or revisit the select box.  

Also styled up the tooltips to be as "round" as the category buttons, adjusted the box-shadow, added a border, and gave the text some line-height to give the eye room to "breath".

### CODE REVIEW

**Comment by jread-usgs** [comment]
@mwernimont please add a screenshot to any PR that changes things visually :+1:

**Comment by mwernimont** [comment]
Are you telling me you don't like mystery and then the big reveal? Lemme guess you read the last page of books first too.

**Comment by mwernimont** [comment]
screen shot 2018-03-02 at 9 27 33 am

**Comment by lindsaycarr** [comment]
can you take a screenshot on your phone and then upload??

**Comment by lindsaycarr** [comment]
Thanks for the fixes to the tooltip :)

**Comment by mwernimont** [comment]
screenshot_2018-03-02-09-45-10

**Comment by mwernimont** [comment]
Sorry, just wanted to fit this in here quick

**Comment by mwernimont** [comment]
screen shot 2018-03-02 at 9 52 06 am

**Comment by jread-usgs** [comment]
Note that social media icons have 90° corners and the rest are rounded (except for the footer, which is 90°).

**Comment by mwernimont** [comment]
Well the icons can be adjusted, and the GitHub logo is always 90, it's just in a square in the social media area. But noted

**Comment by jread-usgs** [comment]
meant the thumbnail in the footer 
image

**Comment by mwernimont** [comment]
oh, dude is serious about his corners, that can change too.

**Pull request merged**
