### PR TITLE
mobile dropdown UI with no functionality

### PR DESCRIPTION
**Pull request by mwernimont**
Dropdowns and zoom-out button in place.  

Made a template for this, as when I was strictly doing D3 to build it but it was getting messy with how many things I needed for the custom select and layout precision.  We can easily add placeholder options in the select this way and D3 can still dynamically add the data to them this way, so didn't see the harm.  If you guys do let me know!

I really wanted to do this myself, but I couldn't easily access the data I wanted and I know you guys could, so didn't see the point in wasting any more time.

### CODE REVIEW

**Comment by lindsaycarr** [comment]
This looks good to me,  but I pulled your branch down and I am getting errors about `updateCircles`. You can still see circles on yours right?

**Comment by lindsaycarr** [comment]
I'm thinking it might be because of @aappling-usgs's PR, which I did not pull down since it has to do with the circles. Or maybe it's some type of merge conflict.

**Comment by aappling-usgs** [comment]
How did you manage to not pull down my PR now that it's merged into master?

**Comment by aappling-usgs** [comment]
Looks to me like somehow this section of the viz.yaml never got updated, or got mismerged, or something:
```yaml
  -
    id: wateruse_page
    ...
    context:
      resources: ["lib_d3_js", "topojson", "header_css", "content_css", "footer_css", "socialCSS","vizlab-favicon",
                  "map_css", "custom_css", "hashes", "projection", "styles", "map_utils", "map_states", "map_counties",
                  "watermark_utils", "circle_utils"]
```
because there shouldn't be a `"circle_utils"` in that list, and there should be a `"map_circles"` in its place (see https://github.com/USGS-VIZLAB/water-use-15/blob/0a0c1fbaac30ebd42255f6c1630dd39e525bacf1/viz.yaml#L223)

This explains the error about updateCircles that Lindsay and I are seeing.

**Comment by aappling-usgs** [comment]
But overall, cool! I think a template is an absolutely appropriate way to do this. I see three next steps:
1) change "circle_utils" to "map_circles" in the viz.yaml, per my previous comment
2) your PR is now several commits behind master , so git pull upstream master and test it out again just to be absolutely sure those recently merged PRs won't break yours
3) There's currently no way to click on a state without also immediately raising a pop-up, and if you zoom out by clicking on the same state, you get a popup again. I think we should make it so that you can only create a popup by clicking when you're zoomed in, and popups disappear when you zoom out. See GIF below for illustration.
4) The Zoom Out button is available even when you're in national view - can we make it appear only when you zoom in?

180409-marty-dropdown

I think tasks 1 and 2 should happen before the current PR is merged. We can push tasks 3 and 4 into new issues unless you think you can resolve them quickly. And I think that Lindsay or I would be mostly qualified to take either of those issues (3 and 4) if you have other higher priority work.

**Comment by aappling-usgs** [comment]
Hmm, and maybe the select county button should only appear once you're in state view, too?

**Comment by jread-usgs** [comment]
Re:pop up comments. Aren’t we dropping the tooltips in favor of the new category selectors anyhow?

**Comment by lindsaycarr** [comment]
@aappling-usgs by "which I did not pull down since it has to do with the circles", I meant when I was testing, so I didn't actually verify that those errors weren't from yours. I see now that that's not the case!

My understanding was that tooltips are staying on desktop and going away on mobile.

**Comment by mwernimont** [comment]
So this PR is just to get the layout in there.  We plan on having the Zoom-out and county selection dropdown to only appear when zoomed into a state.  I just wasn't having an easy time getting to the data I needed to fill in the dropdowns dynamically through D3.  Also wasn't sure of what approach to make that the most efficient process possible, so was either hoping for you @aappling-usgs and @lindsaycarr  to mentor me, or to hook up that functionality yourselves and hand back the task to me when those two specific things were done.  Whichever you find the most appealing to yourselves.

**Comment by jread-usgs** [comment]
I was assuming tooltips were going away completely.

**Comment by lindsaycarr** [comment]
@mwernimont can you do 1 & 2? Then we can get this merged and sort out who does the next bit!

**Comment by lindsaycarr** [comment]
Oh sorry - the comments are making me lose track of everything :)

**Comment by lindsaycarr** [comment]
Looks good and works locally for me! Merging and then I will nominate myself to get going on this one since @aappling-usgs already has #139.

@mwernimont since you're very interested, I will make sure to have you look over the PR I submit for this to take a look at what I've done

**Comment by mwernimont** [comment]
Yes please @lindsaycarr

**Pull request merged**
