### PR TITLE
Url hash tags

### PR DESCRIPTION
**Pull request by aappling-usgs**
Added URL hash tags for water use category. Tags for state were already there. Updated the map title function to reflect current category as well as state.

The default is USA, Total water use:
180227-url-default

You can call the `updateCategory` function in the browser to change the category in both the URL bar and the map title. (This is where @mwernimont can plug in the button functionality - buttons should call `updateCategory()`.)
180227-function-call-zoom

And you can edit the URL directly, or paste in a new URL (not shown) to go to the specified state/national view and water use category:
180227-url-edit-zoom

### CODE REVIEW

**Comment by aappling-usgs** [comment]
This PR contains a pretty small chunk of javascript code and one small D3 call. @ldecicco-USGS , you interested in reviewing for the sake of more exposure to the .js side? Otherwise I nominate @lindsaycarr 

getHash and setHash are defined in js/url_hashes.js. They read/set the values from URL keys ("v" and "c" in this case).

`d3.select(...).text(...)` allows you to set the value of text in an html item.

I'm creating/using three global variables: activeView, activeYear, and activeCategory. (activeYear to be deleted with #41). These store the current vizzy state and are updated within updateView, updateCategory, etc. in js/map_utils.js.

**Comment by aappling-usgs** [comment]
Resolves #14 . Has taken ~2 hours so far.

**Comment by aappling-usgs** [comment]
done :point_up: and back to you, @lindsaycarr

**Comment by lindsaycarr** [comment]
👍 should I merge or wait for Laura to review also?

**Comment by aappling-usgs** [comment]
go ahead and merge, please.

**Pull request merged**
