### PR TITLE
filtering out bad AK county

### PR DESCRIPTION
**Pull request by mwernimont**
@aappling-usgs did you mean add to the filter to be specifically AK or just add the stateFip to the actual projection issue in GitHub?

### CODE REVIEW

**Comment by aappling-usgs** [comment]
i meant to add it to the issue

**Comment by aappling-usgs** [comment]
Can you add a note about how long this took you, and link to the issue where you're adding info about the problem county?

**Comment by mwernimont** [comment]
Took me about 14 hours, as I was going down wrong rabbit holes. Comment in issue here https://github.com/USGS-VIZLAB/water-use-15/issues/9

**Comment by lindsaycarr** [comment]
@mwernimont is this 14 hrs for the PR plus the 4 hrs you mentioned on #9 on March 2 (https://github.com/USGS-VIZLAB/water-use-15/issues/9#issuecomment-369918863)? Just trying to keep track 😄

**Comment by mwernimont** [comment]
I think its 14hrs total.

**Comment by lindsaycarr** [comment]
cool, thanks!

**Pull request merged**
